name: Android Verify PR

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  verify-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up environments
        env:
          GPR_USER: ${{ secrets.GPR_USR }}
          GPR_API_KEY: ${{ secrets.GPR_KEY }}
      - name: Run Unit tests
        run: bash ./gradlew clean spotlessCheck assembleProdDebugAndroidTest testProdDebugUnitTest --stacktrace
